[toolchain]
channel = "1.90"
components = [
  "rustfmt",
  "clippy",
  "rust-src",
  "rust-analyzer",
  "llvm-tools-preview",
]

profile = "minimal"
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin"]
