edition = "2024"
unstable_features = true
error_on_unformatted = true

max_width = 120
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

imports_granularity = "Item"
group_imports = "StdExternalCrate"

normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true

use_field_init_shorthand = true
merge_derives = false
reorder_impl_items = true
overflow_delimited_expr = true
