on-unmatched = "fatal"

excludes = [
  "*.bin",
  ".gitignore",
  "sdkconfig.defaults",
  "devbox.lock",
  "Cargo.lock",
  "LICENSE",
]

[formatter.just]
command = "justfmt"
includes = ["*/justfile", "justfile"]

[formatter.prettier]
command = "prettier"
options = ["--write", "--no-bracket-spacing"]
includes = ["*.json", "*.md", "*.yaml"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]

[formatter.shfmt]
command = "shfmt"
options = ["--write", "--indent", "2"]
includes = [".envrc", "bin/justfmt", "bin/openspec"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
