on-unmatched = "fatal"

excludes = [".gitignore", "devbox.lock", "LICENSE"]

[formatter.just]
command = "just"
options = ["--unstable", "--fmt", "--justfile"]
includes = ["justfile"]

[formatter.prettier]
command = "prettier"
options = ["--write", "--no-bracket-spacing"]
includes = ["*.json", "*.md", "*.yaml"]

[formatter.shfmt]
command = "shfmt"
options = ["--write", "--indent", "2"]
includes = [".envrc", "bin/openspec"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
