[wokwi]
version = 1
elf = "../../target/xtensa-esp32s3-espidf/debug/ariadna"
firmware = "../../target/xtensa-esp32s3-espidf/debug/ariadna"

[[chip]]
name = "gnss-emulator"
binary = "../../target/wasm32-unknown-unknown/release/gnss_emulator.wasm"
